name: Continuous-development

on:
  push:
    branches:
      - development
  schedule:
    - cron:  '0 0 * * *'

jobs:

# Read the content of the file pharo-versions.json. It is interpreted as a json matrix in the next job.
  get-matrix:
    runs-on: ubuntu-latest
    outputs: 
      pharo-version: ${{ steps.get-matrix-from-json.outputs.pharo-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Matrix
        id: get-matrix-from-json          
        run: |
          PHAROVERSION=$(cat $GITHUB_WORKSPACE/.github/workflows/pharo-versions.json)
          echo "::set-output name=pharo-version::$PHAROVERSION"

  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Moose9-development
    strategy:
      matrix:
        smalltalk: ${{ fromJSON(needs.get-matrix.outputs.pharo-version) }}
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15

      - name: set-version
        run: |
          ls -l $SMALLTALK_CI_VM
          $SMALLTALK_CI_VM  $SMALLTALK_CI_IMAGE eval --save "MooseVersion current commitHash: '$GITHUB_SHA'. HelpBrowser allInstances do: #close. MooseWelcome openForRelease"
          
      - name: rename
        run: |
          mv $SMALLTALK_CI_BUILD/* .
          mv TravisCI.image $PROJECT_NAME-${{ matrix.smalltalk }}.image
          mv TravisCI.changes $PROJECT_NAME-${{ matrix.smalltalk }}.changes
          echo ${${{ matrix.smalltalk }}} | sed -e 's/\.//g' > pharo.version
        
      - name: package
        run: |
          zip -r $PROJECT_NAME-${{ matrix.smalltalk }}.zip $PROJECT_NAME-${{ matrix.smalltalk }}.image $PROJECT_NAME-${{ matrix.smalltalk }}.changes *.sources pharo.version
          ls
      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: 'continuous'
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.PROJECT_NAME }}.zip
